export type Hotel = {
  id: number; name: string; area: string; city: string; price: number; oldPrice?: number;
  rating: number; reviews: number; stars: number; badge?: string; image: string;
  tags: string[]; description: string; distance: string; deal?: string
}
const photo = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=85`
export const hotels: Hotel[] = [
 {id:1,name:'The Fern Residency Bengaluru',area:'Whitefield',city:'Bengaluru',price:5290,oldPrice:7600,rating:8.6,reviews:1248,stars:4,badge:'Popular choice',image:photo('photo-1566073771259-6a8506099945'),tags:['Free Wi-Fi','Swimming pool','Breakfast','Free cancellation'],description:'Comfortable modern rooms, thoughtful service and easy access to business hubs.',distance:'1.2 km from city centre',deal:'Limited-time deal'},
 {id:2,name:'Taj MG Road, Bengaluru',area:'MG Road',city:'Bengaluru',price:12800,rating:9.1,reviews:2084,stars:5,image:photo('photo-1542314831-068cd1dbfeeb'),tags:['Free Wi-Fi','Swimming pool','Breakfast','Parking','Spa'],description:'An elegant city retreat with refined dining, a relaxing pool and attentive service.',distance:'0.8 km from city centre',deal:'Member price'},
 {id:3,name:'Bloomrooms @ Indiranagar',area:'Indiranagar',city:'Bengaluru',price:3499,oldPrice:4200,rating:8.2,reviews:976,stars:3,image:photo('photo-1564501049412-61c2a3083791'),tags:['Free Wi-Fi','Free cancellation'],description:'A bright, design-led stay in one of the city’s liveliest neighbourhoods.',distance:'4.1 km from city centre'},
 {id:4,name:'Radisson Blu Atria Bengaluru',area:'Vasanth Nagar',city:'Bengaluru',price:7990,oldPrice:9500,rating:8.5,reviews:1530,stars:5,image:photo('photo-1571896349842-33c89424de2d'),tags:['Free Wi-Fi','Swimming pool','Breakfast','Parking'],description:'Contemporary rooms and excellent facilities close to central Bengaluru.',distance:'1.5 km from city centre'},
 {id:5,name:'The Leela Palace Bengaluru',area:'Old Airport Road',city:'Bengaluru',price:22400,rating:9.3,reviews:1872,stars:5,badge:'Exceptional stay',image:photo('photo-1568084680786-a84f91d1153c'),tags:['Free Wi-Fi','Swimming pool','Breakfast','Parking','Spa'],description:'Palatial gardens, luxurious rooms and standout hospitality in a serene setting.',distance:'6.3 km from city centre',deal:'Special offer'},
 {id:6,name:'ibis Bengaluru City Centre',area:'Sampangi Rama Nagar',city:'Bengaluru',price:4150,rating:7.9,reviews:1116,stars:3,image:photo('photo-1590490360182-c33d57733427'),tags:['Free Wi-Fi','Breakfast','Parking'],description:'A practical, well-connected base for city breaks and work trips.',distance:'1.7 km from city centre'},
 {id:7,name:'Oakwood Premier Prestige',area:'UB City',city:'Bengaluru',price:9800,oldPrice:11200,rating:8.7,reviews:640,stars:5,image:photo('photo-1582719508461-905c673771fd'),tags:['Free Wi-Fi','Swimming pool','Kitchen','Parking'],description:'Spacious serviced apartments with premium amenities near UB City.',distance:'0.6 km from city centre'},
 {id:8,name:'Lemon Tree Hotel Whitefield',area:'Whitefield',city:'Bengaluru',price:3890,rating:7.8,reviews:835,stars:4,image:photo('photo-1611892440504-42a792e24d32'),tags:['Free Wi-Fi','Breakfast','Swimming pool'],description:'A cheerful business-friendly hotel with comfortable rooms and dining.',distance:'14 km from city centre'},
 {id:9,name:'Shangri-La Bengaluru',area:'Vasanth Nagar',city:'Bengaluru',price:15400,rating:9.0,reviews:1241,stars:5,image:photo('photo-1549294413-26f195200c16'),tags:['Free Wi-Fi','Swimming pool','Breakfast','Parking','Spa'],description:'Sophisticated rooms, destination dining and expansive views of the city.',distance:'2.0 km from city centre'},
 {id:10,name:'The Chancery Pavilion',area:'Residency Road',city:'Bengaluru',price:5690,rating:8.0,reviews:794,stars:4,image:photo('photo-1596436889106-be35e843f974'),tags:['Free Wi-Fi','Breakfast','Parking'],description:'A central stay with easy access to shopping, dining and local landmarks.',distance:'1.1 km from city centre'},
 {id:11,name:'Olive Hotel Brookefield',area:'Brookefield',city:'Bengaluru',price:2790,rating:7.7,reviews:428,stars:3,image:photo('photo-1566665797739-1674de7a421a'),tags:['Free Wi-Fi','Free cancellation'],description:'Simple, modern rooms suited to short stays and work visits.',distance:'12 km from city centre'},
 {id:12,name:'Conrad Bengaluru',area:'Ulsoor',city:'Bengaluru',price:17600,rating:9.2,reviews:1053,stars:5,badge:'Top rated',image:photo('photo-1601918774946-25832a4be0d6'),tags:['Free Wi-Fi','Swimming pool','Breakfast','Parking','Spa'],description:'Luxury lakeside hospitality with excellent dining and spacious rooms.',distance:'2.8 km from city centre'},
]
